##Importing Libraries and the Dataset

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/drive/MyDrive/BDA MiniProj/preprocessed_data.csv")

In [4]:
df.head()

Unnamed: 0         short_name  value_eur  wage_eur  preferred_foot  \
0           0           L. Messi   67500000    560000               0   
1           1  Cristiano Ronaldo   46000000    220000               1   
2           2           J. Oblak   75000000    125000               1   
3           3     R. Lewandowski   80000000    240000               1   
4           4          Neymar Jr   90000000    270000               1   

   team_position  weak_foot  skill_moves  age  work_rate  ...  \
0              0          4            4   33          7  ...   
1             13          4            5   35          1  ...   
2              5          3            1   27          8  ...   
3             27          4            4   31          2  ...   
4             14          5            5   28          2  ...   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         35                        24                   6   
1                         32                        24                   7   
2                         12                        18                  87   
3                         42                        19                  15   
4                         30                        29                   9   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    11                   15                       14   
1                    11                   15                       14   
2                    92                   78                       90   
3                     6                   12                        8   
4                     9                   15                       15   

   goalkeeping_reflexes  player_positions  overall  potential  
0                     8        RW, ST, CF       93         93  
1                    11            ST, LW       92         92  
2                    90                GK       91         93  
3                    10                ST       91         91  
4                    11           LW, CAM       91         91  

[5 rows x 59 columns]

In [5]:
nr = df.columns[[0,2,3]]

In [6]:
df.drop(nr,axis=1,inplace=True)

In [7]:
df.head()

short_name  preferred_foot  team_position  weak_foot  skill_moves  \
0           L. Messi               0              0          4            4   
1  Cristiano Ronaldo               1             13          4            5   
2           J. Oblak               1              5          3            1   
3     R. Lewandowski               1             27          4            4   
4          Neymar Jr               1             14          5            5   

   age  work_rate  team_jersey_number  pace  shooting  ...  \
0   33          7                10.0  85.0      92.0  ...   
1   35          1                 7.0  89.0      93.0  ...   
2   27          8                13.0  30.0      30.0  ...   
3   31          2                 9.0  78.0      91.0  ...   
4   28          2                10.0  91.0      85.0  ...   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         35                        24                   6   
1                         32                        24                   7   
2                         12                        18                  87   
3                         42                        19                  15   
4                         30                        29                   9   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    11                   15                       14   
1                    11                   15                       14   
2                    92                   78                       90   
3                     6                   12                        8   
4                     9                   15                       15   

   goalkeeping_reflexes  player_positions  overall  potential  
0                     8        RW, ST, CF       93         93  
1                    11            ST, LW       92         92  
2                    90                GK       91         93  
3                    10                ST       91         91  
4                    11           LW, CAM       91         91  

[5 rows x 56 columns]

In [8]:
df.shape

(18719, 56)

In [9]:
df.work_rate.unique()

array([7, 1, 8, 2, 0, 6, 3, 5, 4])

In [10]:
df.team_position.unique()

array([ 0, 13,  5, 27, 14, 19,  8, 25, 28,  3,  2, 20, 24,  9, 17,  7, 12,
       18, 11,  1, 23, 10, 22, 21, 15,  4,  6, 26, 16])

In [11]:
df.preferred_foot.unique()

array([0, 1])

##Traing Model

In [12]:
X1 = df.iloc[:,1:53].values
X2 = df.iloc[:,2:53].values
X3 = df.iloc[:,2:53].values
y1 = df.iloc[:,53].values
y2 = df.iloc[:,54].values
y3 = df.iloc[:,55].values

In [13]:
print(y2)

[93 92 91 ... 47 47 47]


In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1 = sc.fit_transform(X1)
X2 = sc.fit_transform(X2)
X3 = sc.fit_transform(X3)

In [15]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=0)
classifier.fit(X1,y1)

SVC(random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 1)
X2_poly = poly_reg.fit_transform(X2)
lin_reg = LinearRegression()
regressor1 = lin_reg.fit(X2_poly,y2)

In [17]:
poly_reg_ = PolynomialFeatures(degree = 1)
X3_poly = poly_reg_.fit_transform(X3)
lin_reg = LinearRegression()
regressor2 = lin_reg.fit(X3_poly,y3)

##Importing the Non-Professional Player dataset

In [18]:
df2 = pd.read_csv("/content/drive/MyDrive/BDA MiniProj/non-professional - non-professional.csv")
df2.head()

short_name preferred_foot team_position  weak_foot  skill_moves  \
0       Ilias Akhomach           Left            RW          4            4   
1              Ez Abde          Right            LW          4            4   
2      Matheus Pereira           Left           RAM          3            3   
3  Maarten Vandevoordt          Right            GK          2            1   
4        M Morgenstern          Right            CB          2            2   

   age      work_rate  team_jersey_number  pace  shooting  ...  \
0   17  Medium/Medium                  27    85        70  ...   
1   20    High/Medium                  20    85        75  ...   
2   23  Medium/Medium                  12    74        80  ...   
3   21        Low/Low                   1    54        20  ...   
4   20    Medium/High                   4    21        34  ...   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         40                        40                  10   
1                         44                        45                  13   
2                         64                        60                  18   
3                         51                        29                  28   
4                         43                        47                  16   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    10                   15                       11   
1                    12                    9                       13   
2                    10                   12                        9   
3                    10                   33                       25   
4                    29                   19                       25   

   goalkeeping_reflexes  player_positions  overall  potential  
0                     8               NaN      NaN        NaN  
1                    15               NaN      NaN        NaN  
2                     9               NaN      NaN        NaN  
3                    10               NaN      NaN        NaN  
4                    54               NaN      NaN        NaN  

[5 rows x 56 columns]

##Encoding the Categorical Data

In [ ]:
objList = df2.select_dtypes(include = "object").columns
print (objList)

Index(['short_name', 'preferred_foot', 'team_position', 'work_rate'], dtype='object')


In [ ]:
a = {'Medium/Low':7, 'High/Low':1, 'Medium/Medium':8, 'High/Medium':2,
       'High/High':0, 'Medium/High':6, 'Low/High':3, 'Low/Medium':5, 'Low/Low':4}
b = {'CAM':0, 'LS':13, 'GK':5, 'ST':27, 'LW':14, 'RCM':19, 'LCB':8, 'RW':25, 'SUB':28, 'CF':3,
       'CDM':2, 'RDM':20, 'RS':24, 'LCM':9, 'RB':17, 'LB':7, 'LM':12, 'RCB':18, 'LF':11, 'CB':1,
       'RM':23, 'LDM':10, 'RF':22, 'RES':21, 'LWB':15, 'CM':4, 'LAM':6, 'RWB':26, 'RAM':16}
c = {'Left':0,'Right':1}
df2['work_rate'] = df2['work_rate'].map(a)
df2['team_position'] = df2['team_position'].map(b)
df2['preferred_foot'] = df2['preferred_foot'].map(c)

In [ ]:
df2

short_name  preferred_foot  team_position  weak_foot  skill_moves  \
0       Ilias Akhomach               0             25          4            4   
1              Ez Abde               1             14          4            4   
2      Matheus Pereira               0             16          3            3   
3  Maarten Vandevoordt               1              5          2            1   
4        M Morgenstern               1              1          2            2   
5              V dican               1              7          3            3   
6              J seelt               0              1          4            2   
7             L Stanga               1             27          3            4   
8          Manu Martos               0              4          3            5   

   age  work_rate  team_jersey_number  pace  shooting  ...  \
0   17          8                  27    85        70  ...   
1   20          2                  20    85        75  ...   
2   23          8                  12    74        80  ...   
3   21          4                   1    54        20  ...   
4   20          6                   4    21        34  ...   
5   20          8                  45    71        10  ...   
6   18          0                  54    67        44  ...   
7   19          1                  65    76        56  ...   
8   24          0                  33    69        63  ...   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         40                        40                  10   
1                         44                        45                  13   
2                         64                        60                  18   
3                         51                        29                  28   
4                         43                        47                  16   
5                         19                        36                  54   
6                         14                        30                  14   
7                         76                        45                  25   
8                         20                        55                  31   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    10                   15                       11   
1                    12                    9                       13   
2                    10                   12                        9   
3                    10                   33                       25   
4                    29                   19                       25   
5                    38                   27                       53   
6                    24                   58                       44   
7                    43                   33                       20   
8                    36                   31                       12   

   goalkeeping_reflexes  player_positions  overall  potential  
0                     8               NaN      NaN        NaN  
1                    15               NaN      NaN        NaN  
2                     9               NaN      NaN        NaN  
3                    10               NaN      NaN        NaN  
4                    54               NaN      NaN        NaN  
5                    20               NaN      NaN        NaN  
6                    39               NaN      NaN        NaN  
7                    34               NaN      NaN        NaN  
8                    34               NaN      NaN        NaN  

[9 rows x 56 columns]

##Predicting the Result

In [ ]:
df2.columns.get_loc('player_positions')

53

In [ ]:
X1_ = df2.iloc[:,1:53].values
X2_ = df2.iloc[:,2:53].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X1_ = sc.fit_transform(X1_)
X2_ = sc.fit_transform(X2_)

In [ ]:
y1_pred = classifier.predict(X1_)

In [ ]:
df2['player_positions'][0]

nan

In [ ]:
for i in range(len(y1_pred)):
  df2['player_positions'][i] = y1_pred[i]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [ ]:
y_pred = regressor1.predict(poly_reg.fit_transform(X2_))

In [ ]:
for i in range(len(y_pred)):
  df2['overall'][i] = int(y_pred[i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
y_pred2 = regressor2.predict(poly_reg_.fit_transform(X2_))

In [ ]:
for i in range(len(y_pred2)):
  df2['potential'][i] = int(y_pred2[i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
df2

short_name  preferred_foot  team_position  weak_foot  skill_moves  \
0       Ilias Akhomach               0             25          4            4   
1              Ez Abde               1             14          4            4   
2      Matheus Pereira               0             16          3            3   
3  Maarten Vandevoordt               1              5          2            1   
4        M Morgenstern               1              1          2            2   
5              V dican               1              7          3            3   
6              J seelt               0              1          4            2   
7             L Stanga               1             27          3            4   
8          Manu Martos               0              4          3            5   

   age  work_rate  team_jersey_number  pace  shooting  ...  \
0   17          8                  27    85        70  ...   
1   20          2                  20    85        75  ...   
2   23          8                  12    74        80  ...   
3   21          4                   1    54        20  ...   
4   20          6                   4    21        34  ...   
5   20          8                  45    71        10  ...   
6   18          0                  54    67        44  ...   
7   19          1                  65    76        56  ...   
8   24          0                  33    69        63  ...   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         40                        40                  10   
1                         44                        45                  13   
2                         64                        60                  18   
3                         51                        29                  28   
4                         43                        47                  16   
5                         19                        36                  54   
6                         14                        30                  14   
7                         76                        45                  25   
8                         20                        55                  31   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    10                   15                       11   
1                    12                    9                       13   
2                    10                   12                        9   
3                    10                   33                       25   
4                    29                   19                       25   
5                    38                   27                       53   
6                    24                   58                       44   
7                    43                   33                       20   
8                    36                   31                       12   

   goalkeeping_reflexes  player_positions  overall  potential  
0                     8            LM, RM     72.0       85.0  
1                    15                RM     77.0       82.0  
2                     9                LB     78.0       77.0  
3                    10                CB     69.0       74.0  
4                    54                CM     78.0       87.0  
5                    20                RB     46.0       50.0  
6                    39               CAM     59.0       70.0  
7                    34                ST     60.0       66.0  
8                    34                LB     47.0       44.0  

[9 rows x 56 columns]